export { default as CorrectIcon } from './CorrectIcon'
export { default as FalseIcon } from './FalseIcon'
export { default as Stars } from './Stars'
export { default as IntroText } from './IntroText/IntroText'
export { default as QuestionText } from './QuestionText/QuestionText'