export { default as CorrectIcon } from './CorrectIcon'
export { default as FalseIcon } from './FalseIcon'
export { default as Stars } from './Stars'
export { default as IntroText } from './IntroText/IntroText'
export { default as QuestionText } from './QuestionText/QuestionText'
export { default as Button } from './Button/Button'
export { default as OutroText } from './OutroText/OutroText'
export { default as Disclaimer } from './Disclaimer/Disclaimer'